version: "3.8"

services:
  db:
    image: postgres:16.0-alpine
    env_file:
      - .env.test
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test
    environment:
      SQL_HOST: db
      SQL_PORT: 5432
    env_file:
      - .env.test
    command: pytest
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  db-data:
