version: "3.8"

services:
  db:
    image: postgres:16.0-alpine
    env_file:
      - /home/deployer/.env.prod
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  prod:
    image: ghcr.io/REPO:main
    environment:
      SQL_HOST: db
      SQL_PORT: 5432
    env_file:
      - /home/deployer/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
